#!/usr/bin/env python3
"""Train the first cheap Forge action-value model from forge-lab JSONL.

Usage:
  python scripts/train_action_ranker.py forge-training.jsonl --out-dir models/forge-v1

The dataset is generated by:
  cargo run --release -p libmtg-forge --bin forge-lab -- generate-training \
      apps/libmtg-forge/examples/forge-tezzeret.txt forge-training.jsonl \
      --games 10000 --rollouts 4

This is intentionally a small tabular baseline. Search remains the teacher;
the model learns to imitate search scores so it can later prune candidate moves.
"""

import argparse
import json
from pathlib import Path

import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error


def load_records(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                yield json.loads(line)


def build_rows(records):
    records = list(records)
    versions = sorted({r.get("evaluator_version", "unknown") for r in records})
    if len(versions) > 1:
        raise ValueError(f"dataset mixes evaluator versions: {versions}")
    if versions and versions[0] != "forge_eval_v2":
        raise ValueError(
            f"expected forge_eval_v2 training labels, found {versions[0]!r}; "
            "regenerate the dataset with the v2 evaluator"
        )
    cards = sorted({
        card
        for r in records
        for zone in (r.get("hand", []), r.get("battlefield", []))
        for card in zone
    })
    actions = sorted({c["action"] for r in records for c in r.get("candidates", [])})

    rows = []
    for r in records:
        hand_counts = {c: r.get("hand", []).count(c) for c in cards}
        board_counts = {c: r.get("battlefield", []).count(c) for c in cards}
        for c in r.get("candidates", []):
            row = {
                "game_index": int(r.get("game_index", 0)),
                "decision_index": int(r.get("decision_index", 0)),
                "turn": int(r.get("turn", 0)),
                "life": int(r.get("life", 20)),
                "opponent_life": int(r.get("opponent_life", 20)),
                "potential_mana": int(r.get("potential_mana", 0)),
                "next_turn_mana": float(r.get("next_turn_mana", 0.0)),
                "artifact_count": int(r.get("artifact_count", 0)),
                "metalcraft": int(bool(r.get("metalcraft", False))),
                "forge_active": int(bool(r.get("forge_active", False))),
                "state_score_before": float(r.get("state_score_before", 0.0)),
                "final_score": float(r.get("final_score", 0.0)),
                "action": c["action"],
                "target_score": float(c["score"]),
            }
            for card in cards:
                row[f"hand::{card}"] = hand_counts[card]
                row[f"board::{card}"] = board_counts[card]
            rows.append(row)
    return pd.DataFrame(rows), cards, actions


def top_action_agreement(frame, pred):
    tmp = frame[["game_index", "decision_index", "action", "target_score"]].copy()
    tmp["prediction"] = pred
    agreed = 0
    total = 0
    for _, group in tmp.groupby(["game_index", "decision_index"], sort=False):
        if len(group) < 2:
            continue
        true_action = group.loc[group["target_score"].idxmax(), "action"]
        pred_action = group.loc[group["prediction"].idxmax(), "action"]
        agreed += int(true_action == pred_action)
        total += 1
    return agreed / total if total else float("nan")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dataset", type=Path)
    ap.add_argument("--out-dir", type=Path, default=Path("models/forge-v1"))
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    df, cards, actions = build_rows(load_records(args.dataset))
    if df.empty:
        raise SystemExit("dataset contains no candidate-action rows")

    # Split by game, not by row, so decisions from the same simulated game do
    # not leak between train and validation.
    game_ids = np.array(sorted(df["game_index"].unique()))
    rng = np.random.default_rng(args.seed)
    rng.shuffle(game_ids)
    cut = max(1, int(len(game_ids) * 0.8))
    train_games = set(game_ids[:cut])
    train_mask = df["game_index"].isin(train_games)

    # One-hot action identity. Hand/battlefield card counts are already numeric.
    feature_df = pd.get_dummies(
        df.drop(columns=["target_score", "game_index", "decision_index", "final_score"]),
        columns=["action"],
        dtype=np.int8,
    )
    X_train = feature_df[train_mask]
    X_val = feature_df[~train_mask]
    y_train = df.loc[train_mask, "target_score"]
    y_val = df.loc[~train_mask, "target_score"]

    model = lgb.LGBMRegressor(
        objective="regression_l1",
        n_estimators=400,
        learning_rate=0.04,
        num_leaves=31,
        max_depth=-1,
        subsample=0.9,
        colsample_bytree=0.9,
        random_state=args.seed,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)

    pred = model.predict(X_val)
    mae = mean_absolute_error(y_val, pred) if len(y_val) else float("nan")
    agreement = top_action_agreement(df.loc[~train_mask], pred) if len(y_val) else float("nan")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    model.booster_.save_model(str(args.out_dir / "action_value.txt"))
    metadata = {
        "feature_columns": list(feature_df.columns),
        "card_vocabulary": cards,
        "action_vocabulary": actions,
        "train_games": int(len(train_games)),
        "validation_games": int(len(game_ids) - len(train_games)),
        "candidate_rows": int(len(df)),
        "validation_mae": None if np.isnan(mae) else float(mae),
        "top_action_agreement": None if np.isnan(agreement) else float(agreement),
    }
    (args.out_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
